// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TopicDTO.proto

package com.yumfee.extremeworld.proto;

public final class TopicProto {
  private TopicProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TopicDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yumfee.extremeworld.proto.TopicDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required string type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional string magicType = 3;</code>
     */
    boolean hasMagicType();
    /**
     * <code>optional string magicType = 3;</code>
     */
    java.lang.String getMagicType();
    /**
     * <code>optional string magicType = 3;</code>
     */
    com.google.protobuf.ByteString
        getMagicTypeBytes();

    /**
     * <code>required string title = 4;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 4;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 4;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>required string content = 5;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 5;</code>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 5;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>required int32 imageCount = 6;</code>
     */
    boolean hasImageCount();
    /**
     * <code>required int32 imageCount = 6;</code>
     */
    int getImageCount();

    /**
     * <code>required int32 replyCount = 7;</code>
     */
    boolean hasReplyCount();
    /**
     * <code>required int32 replyCount = 7;</code>
     */
    int getReplyCount();

    /**
     * <code>required int32 allReplyCount = 8;</code>
     */
    boolean hasAllReplyCount();
    /**
     * <code>required int32 allReplyCount = 8;</code>
     */
    int getAllReplyCount();

    /**
     * <code>required int32 viewCount = 9;</code>
     */
    boolean hasViewCount();
    /**
     * <code>required int32 viewCount = 9;</code>
     */
    int getViewCount();

    /**
     * <code>required int32 agreeCount = 10;</code>
     */
    boolean hasAgreeCount();
    /**
     * <code>required int32 agreeCount = 10;</code>
     */
    int getAgreeCount();

    /**
     * <code>required string createTime = 11;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>required string createTime = 11;</code>
     */
    java.lang.String getCreateTime();
    /**
     * <code>required string createTime = 11;</code>
     */
    com.google.protobuf.ByteString
        getCreateTimeBytes();

    /**
     * <code>required int32 status = 12;</code>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 12;</code>
     */
    int getStatus();

    /**
     * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
     */
    boolean hasUser();
    /**
     * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
     */
    com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO getUser();
    /**
     * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
     */
    com.yumfee.extremeworld.proto.UserMinProto.UserMinDTOOrBuilder getUserOrBuilder();

    /**
     * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
     */
    boolean hasVideoDetail();
    /**
     * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
     */
    com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO getVideoDetail();
    /**
     * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
     */
    com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTOOrBuilder getVideoDetailOrBuilder();

    /**
     * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
     */
    boolean hasMediaWrap();
    /**
     * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
     */
    com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO getMediaWrap();
    /**
     * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
     */
    com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTOOrBuilder getMediaWrapOrBuilder();

    /**
     * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
     */
    boolean hasTaxonomy();
    /**
     * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
     */
    com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO getTaxonomy();
    /**
     * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
     */
    com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTOOrBuilder getTaxonomyOrBuilder();

    /**
     * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
     */
    boolean hasCourse();
    /**
     * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
     */
    com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO getCourse();
    /**
     * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
     */
    com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTOOrBuilder getCourseOrBuilder();
  }
  /**
   * Protobuf type {@code com.yumfee.extremeworld.proto.TopicDTO}
   */
  public static final class TopicDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.yumfee.extremeworld.proto.TopicDTO)
      TopicDTOOrBuilder {
    // Use TopicDTO.newBuilder() to construct.
    private TopicDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TopicDTO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TopicDTO defaultInstance;
    public static TopicDTO getDefaultInstance() {
      return defaultInstance;
    }

    public TopicDTO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TopicDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              type_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              magicType_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              title_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              content_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              imageCount_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              replyCount_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              allReplyCount_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              viewCount_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              agreeCount_ = input.readInt32();
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              createTime_ = bs;
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              status_ = input.readInt32();
              break;
            }
            case 106: {
              com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00001000) == 0x00001000)) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00001000;
              break;
            }
            case 114: {
              com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00002000) == 0x00002000)) {
                subBuilder = videoDetail_.toBuilder();
              }
              videoDetail_ = input.readMessage(com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(videoDetail_);
                videoDetail_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00002000;
              break;
            }
            case 122: {
              com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00004000) == 0x00004000)) {
                subBuilder = mediaWrap_.toBuilder();
              }
              mediaWrap_ = input.readMessage(com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mediaWrap_);
                mediaWrap_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00004000;
              break;
            }
            case 130: {
              com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00008000) == 0x00008000)) {
                subBuilder = taxonomy_.toBuilder();
              }
              taxonomy_ = input.readMessage(com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(taxonomy_);
                taxonomy_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00008000;
              break;
            }
            case 138: {
              com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00010000) == 0x00010000)) {
                subBuilder = course_.toBuilder();
              }
              course_ = input.readMessage(com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(course_);
                course_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00010000;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yumfee.extremeworld.proto.TopicProto.internal_static_com_yumfee_extremeworld_proto_TopicDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yumfee.extremeworld.proto.TopicProto.internal_static_com_yumfee_extremeworld_proto_TopicDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yumfee.extremeworld.proto.TopicProto.TopicDTO.class, com.yumfee.extremeworld.proto.TopicProto.TopicDTO.Builder.class);
    }

    public static com.google.protobuf.Parser<TopicDTO> PARSER =
        new com.google.protobuf.AbstractParser<TopicDTO>() {
      public TopicDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TopicDTO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TopicDTO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private java.lang.Object type_;
    /**
     * <code>required string type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAGICTYPE_FIELD_NUMBER = 3;
    private java.lang.Object magicType_;
    /**
     * <code>optional string magicType = 3;</code>
     */
    public boolean hasMagicType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string magicType = 3;</code>
     */
    public java.lang.String getMagicType() {
      java.lang.Object ref = magicType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          magicType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string magicType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMagicTypeBytes() {
      java.lang.Object ref = magicType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        magicType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 4;
    private java.lang.Object title_;
    /**
     * <code>required string title = 4;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string title = 4;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private java.lang.Object content_;
    /**
     * <code>required string content = 5;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string content = 5;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGECOUNT_FIELD_NUMBER = 6;
    private int imageCount_;
    /**
     * <code>required int32 imageCount = 6;</code>
     */
    public boolean hasImageCount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 imageCount = 6;</code>
     */
    public int getImageCount() {
      return imageCount_;
    }

    public static final int REPLYCOUNT_FIELD_NUMBER = 7;
    private int replyCount_;
    /**
     * <code>required int32 replyCount = 7;</code>
     */
    public boolean hasReplyCount() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 replyCount = 7;</code>
     */
    public int getReplyCount() {
      return replyCount_;
    }

    public static final int ALLREPLYCOUNT_FIELD_NUMBER = 8;
    private int allReplyCount_;
    /**
     * <code>required int32 allReplyCount = 8;</code>
     */
    public boolean hasAllReplyCount() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 allReplyCount = 8;</code>
     */
    public int getAllReplyCount() {
      return allReplyCount_;
    }

    public static final int VIEWCOUNT_FIELD_NUMBER = 9;
    private int viewCount_;
    /**
     * <code>required int32 viewCount = 9;</code>
     */
    public boolean hasViewCount() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 viewCount = 9;</code>
     */
    public int getViewCount() {
      return viewCount_;
    }

    public static final int AGREECOUNT_FIELD_NUMBER = 10;
    private int agreeCount_;
    /**
     * <code>required int32 agreeCount = 10;</code>
     */
    public boolean hasAgreeCount() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int32 agreeCount = 10;</code>
     */
    public int getAgreeCount() {
      return agreeCount_;
    }

    public static final int CREATETIME_FIELD_NUMBER = 11;
    private java.lang.Object createTime_;
    /**
     * <code>required string createTime = 11;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string createTime = 11;</code>
     */
    public java.lang.String getCreateTime() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          createTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string createTime = 11;</code>
     */
    public com.google.protobuf.ByteString
        getCreateTimeBytes() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 12;
    private int status_;
    /**
     * <code>required int32 status = 12;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required int32 status = 12;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int USER_FIELD_NUMBER = 13;
    private com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO user_;
    /**
     * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
     */
    public com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO getUser() {
      return user_;
    }
    /**
     * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
     */
    public com.yumfee.extremeworld.proto.UserMinProto.UserMinDTOOrBuilder getUserOrBuilder() {
      return user_;
    }

    public static final int VIDEODETAIL_FIELD_NUMBER = 14;
    private com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO videoDetail_;
    /**
     * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
     */
    public boolean hasVideoDetail() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
     */
    public com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO getVideoDetail() {
      return videoDetail_;
    }
    /**
     * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
     */
    public com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTOOrBuilder getVideoDetailOrBuilder() {
      return videoDetail_;
    }

    public static final int MEDIAWRAP_FIELD_NUMBER = 15;
    private com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO mediaWrap_;
    /**
     * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
     */
    public boolean hasMediaWrap() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
     */
    public com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO getMediaWrap() {
      return mediaWrap_;
    }
    /**
     * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
     */
    public com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTOOrBuilder getMediaWrapOrBuilder() {
      return mediaWrap_;
    }

    public static final int TAXONOMY_FIELD_NUMBER = 16;
    private com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO taxonomy_;
    /**
     * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
     */
    public boolean hasTaxonomy() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
     */
    public com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO getTaxonomy() {
      return taxonomy_;
    }
    /**
     * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
     */
    public com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTOOrBuilder getTaxonomyOrBuilder() {
      return taxonomy_;
    }

    public static final int COURSE_FIELD_NUMBER = 17;
    private com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO course_;
    /**
     * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
     */
    public boolean hasCourse() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
     */
    public com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO getCourse() {
      return course_;
    }
    /**
     * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
     */
    public com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTOOrBuilder getCourseOrBuilder() {
      return course_;
    }

    private void initFields() {
      id_ = 0L;
      type_ = "";
      magicType_ = "";
      title_ = "";
      content_ = "";
      imageCount_ = 0;
      replyCount_ = 0;
      allReplyCount_ = 0;
      viewCount_ = 0;
      agreeCount_ = 0;
      createTime_ = "";
      status_ = 0;
      user_ = com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.getDefaultInstance();
      videoDetail_ = com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.getDefaultInstance();
      mediaWrap_ = com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.getDefaultInstance();
      taxonomy_ = com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.getDefaultInstance();
      course_ = com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasImageCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReplyCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAllReplyCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasViewCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAgreeCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUser().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasVideoDetail()) {
        if (!getVideoDetail().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasMediaWrap()) {
        if (!getMediaWrap().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMagicTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getContentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, imageCount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, replyCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, allReplyCount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, viewCount_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, agreeCount_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getCreateTimeBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, status_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeMessage(13, user_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeMessage(14, videoDetail_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeMessage(15, mediaWrap_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeMessage(16, taxonomy_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeMessage(17, course_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMagicTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getContentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, imageCount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, replyCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, allReplyCount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, viewCount_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, agreeCount_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getCreateTimeBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, status_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, user_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, videoDetail_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, mediaWrap_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, taxonomy_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(17, course_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yumfee.extremeworld.proto.TopicProto.TopicDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yumfee.extremeworld.proto.TopicProto.TopicDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yumfee.extremeworld.proto.TopicProto.TopicDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yumfee.extremeworld.proto.TopicProto.TopicDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yumfee.extremeworld.proto.TopicProto.TopicDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yumfee.extremeworld.proto.TopicProto.TopicDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yumfee.extremeworld.proto.TopicProto.TopicDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yumfee.extremeworld.proto.TopicProto.TopicDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yumfee.extremeworld.proto.TopicProto.TopicDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yumfee.extremeworld.proto.TopicProto.TopicDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yumfee.extremeworld.proto.TopicProto.TopicDTO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yumfee.extremeworld.proto.TopicDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yumfee.extremeworld.proto.TopicDTO)
        com.yumfee.extremeworld.proto.TopicProto.TopicDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yumfee.extremeworld.proto.TopicProto.internal_static_com_yumfee_extremeworld_proto_TopicDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yumfee.extremeworld.proto.TopicProto.internal_static_com_yumfee_extremeworld_proto_TopicDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yumfee.extremeworld.proto.TopicProto.TopicDTO.class, com.yumfee.extremeworld.proto.TopicProto.TopicDTO.Builder.class);
      }

      // Construct using com.yumfee.extremeworld.proto.TopicProto.TopicDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
          getVideoDetailFieldBuilder();
          getMediaWrapFieldBuilder();
          getTaxonomyFieldBuilder();
          getCourseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        magicType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        imageCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        replyCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        allReplyCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        viewCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        agreeCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        createTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        if (userBuilder_ == null) {
          user_ = com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.getDefaultInstance();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00001000);
        if (videoDetailBuilder_ == null) {
          videoDetail_ = com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.getDefaultInstance();
        } else {
          videoDetailBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00002000);
        if (mediaWrapBuilder_ == null) {
          mediaWrap_ = com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.getDefaultInstance();
        } else {
          mediaWrapBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00004000);
        if (taxonomyBuilder_ == null) {
          taxonomy_ = com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.getDefaultInstance();
        } else {
          taxonomyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00008000);
        if (courseBuilder_ == null) {
          course_ = com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.getDefaultInstance();
        } else {
          courseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yumfee.extremeworld.proto.TopicProto.internal_static_com_yumfee_extremeworld_proto_TopicDTO_descriptor;
      }

      public com.yumfee.extremeworld.proto.TopicProto.TopicDTO getDefaultInstanceForType() {
        return com.yumfee.extremeworld.proto.TopicProto.TopicDTO.getDefaultInstance();
      }

      public com.yumfee.extremeworld.proto.TopicProto.TopicDTO build() {
        com.yumfee.extremeworld.proto.TopicProto.TopicDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yumfee.extremeworld.proto.TopicProto.TopicDTO buildPartial() {
        com.yumfee.extremeworld.proto.TopicProto.TopicDTO result = new com.yumfee.extremeworld.proto.TopicProto.TopicDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.magicType_ = magicType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.imageCount_ = imageCount_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.replyCount_ = replyCount_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.allReplyCount_ = allReplyCount_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.viewCount_ = viewCount_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.agreeCount_ = agreeCount_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        if (videoDetailBuilder_ == null) {
          result.videoDetail_ = videoDetail_;
        } else {
          result.videoDetail_ = videoDetailBuilder_.build();
        }
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        if (mediaWrapBuilder_ == null) {
          result.mediaWrap_ = mediaWrap_;
        } else {
          result.mediaWrap_ = mediaWrapBuilder_.build();
        }
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        if (taxonomyBuilder_ == null) {
          result.taxonomy_ = taxonomy_;
        } else {
          result.taxonomy_ = taxonomyBuilder_.build();
        }
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        if (courseBuilder_ == null) {
          result.course_ = course_;
        } else {
          result.course_ = courseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yumfee.extremeworld.proto.TopicProto.TopicDTO) {
          return mergeFrom((com.yumfee.extremeworld.proto.TopicProto.TopicDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yumfee.extremeworld.proto.TopicProto.TopicDTO other) {
        if (other == com.yumfee.extremeworld.proto.TopicProto.TopicDTO.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000002;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasMagicType()) {
          bitField0_ |= 0x00000004;
          magicType_ = other.magicType_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000008;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000010;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasImageCount()) {
          setImageCount(other.getImageCount());
        }
        if (other.hasReplyCount()) {
          setReplyCount(other.getReplyCount());
        }
        if (other.hasAllReplyCount()) {
          setAllReplyCount(other.getAllReplyCount());
        }
        if (other.hasViewCount()) {
          setViewCount(other.getViewCount());
        }
        if (other.hasAgreeCount()) {
          setAgreeCount(other.getAgreeCount());
        }
        if (other.hasCreateTime()) {
          bitField0_ |= 0x00000400;
          createTime_ = other.createTime_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasVideoDetail()) {
          mergeVideoDetail(other.getVideoDetail());
        }
        if (other.hasMediaWrap()) {
          mergeMediaWrap(other.getMediaWrap());
        }
        if (other.hasTaxonomy()) {
          mergeTaxonomy(other.getTaxonomy());
        }
        if (other.hasCourse()) {
          mergeCourse(other.getCourse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        if (!hasImageCount()) {
          
          return false;
        }
        if (!hasReplyCount()) {
          
          return false;
        }
        if (!hasAllReplyCount()) {
          
          return false;
        }
        if (!hasViewCount()) {
          
          return false;
        }
        if (!hasAgreeCount()) {
          
          return false;
        }
        if (!hasCreateTime()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasUser()) {
          
          return false;
        }
        if (!getUser().isInitialized()) {
          
          return false;
        }
        if (hasVideoDetail()) {
          if (!getVideoDetail().isInitialized()) {
            
            return false;
          }
        }
        if (hasMediaWrap()) {
          if (!getMediaWrap().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yumfee.extremeworld.proto.TopicProto.TopicDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yumfee.extremeworld.proto.TopicProto.TopicDTO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object magicType_ = "";
      /**
       * <code>optional string magicType = 3;</code>
       */
      public boolean hasMagicType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string magicType = 3;</code>
       */
      public java.lang.String getMagicType() {
        java.lang.Object ref = magicType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            magicType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string magicType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMagicTypeBytes() {
        java.lang.Object ref = magicType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          magicType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string magicType = 3;</code>
       */
      public Builder setMagicType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        magicType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string magicType = 3;</code>
       */
      public Builder clearMagicType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        magicType_ = getDefaultInstance().getMagicType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string magicType = 3;</code>
       */
      public Builder setMagicTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        magicType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 4;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string title = 4;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 4;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 4;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 4;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 5;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string content = 5;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 5;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 5;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 5;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 5;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
        return this;
      }

      private int imageCount_ ;
      /**
       * <code>required int32 imageCount = 6;</code>
       */
      public boolean hasImageCount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 imageCount = 6;</code>
       */
      public int getImageCount() {
        return imageCount_;
      }
      /**
       * <code>required int32 imageCount = 6;</code>
       */
      public Builder setImageCount(int value) {
        bitField0_ |= 0x00000020;
        imageCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 imageCount = 6;</code>
       */
      public Builder clearImageCount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        imageCount_ = 0;
        onChanged();
        return this;
      }

      private int replyCount_ ;
      /**
       * <code>required int32 replyCount = 7;</code>
       */
      public boolean hasReplyCount() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 replyCount = 7;</code>
       */
      public int getReplyCount() {
        return replyCount_;
      }
      /**
       * <code>required int32 replyCount = 7;</code>
       */
      public Builder setReplyCount(int value) {
        bitField0_ |= 0x00000040;
        replyCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 replyCount = 7;</code>
       */
      public Builder clearReplyCount() {
        bitField0_ = (bitField0_ & ~0x00000040);
        replyCount_ = 0;
        onChanged();
        return this;
      }

      private int allReplyCount_ ;
      /**
       * <code>required int32 allReplyCount = 8;</code>
       */
      public boolean hasAllReplyCount() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 allReplyCount = 8;</code>
       */
      public int getAllReplyCount() {
        return allReplyCount_;
      }
      /**
       * <code>required int32 allReplyCount = 8;</code>
       */
      public Builder setAllReplyCount(int value) {
        bitField0_ |= 0x00000080;
        allReplyCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 allReplyCount = 8;</code>
       */
      public Builder clearAllReplyCount() {
        bitField0_ = (bitField0_ & ~0x00000080);
        allReplyCount_ = 0;
        onChanged();
        return this;
      }

      private int viewCount_ ;
      /**
       * <code>required int32 viewCount = 9;</code>
       */
      public boolean hasViewCount() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 viewCount = 9;</code>
       */
      public int getViewCount() {
        return viewCount_;
      }
      /**
       * <code>required int32 viewCount = 9;</code>
       */
      public Builder setViewCount(int value) {
        bitField0_ |= 0x00000100;
        viewCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 viewCount = 9;</code>
       */
      public Builder clearViewCount() {
        bitField0_ = (bitField0_ & ~0x00000100);
        viewCount_ = 0;
        onChanged();
        return this;
      }

      private int agreeCount_ ;
      /**
       * <code>required int32 agreeCount = 10;</code>
       */
      public boolean hasAgreeCount() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int32 agreeCount = 10;</code>
       */
      public int getAgreeCount() {
        return agreeCount_;
      }
      /**
       * <code>required int32 agreeCount = 10;</code>
       */
      public Builder setAgreeCount(int value) {
        bitField0_ |= 0x00000200;
        agreeCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 agreeCount = 10;</code>
       */
      public Builder clearAgreeCount() {
        bitField0_ = (bitField0_ & ~0x00000200);
        agreeCount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object createTime_ = "";
      /**
       * <code>required string createTime = 11;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required string createTime = 11;</code>
       */
      public java.lang.String getCreateTime() {
        java.lang.Object ref = createTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            createTime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string createTime = 11;</code>
       */
      public com.google.protobuf.ByteString
          getCreateTimeBytes() {
        java.lang.Object ref = createTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string createTime = 11;</code>
       */
      public Builder setCreateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string createTime = 11;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000400);
        createTime_ = getDefaultInstance().getCreateTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string createTime = 11;</code>
       */
      public Builder setCreateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        createTime_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>required int32 status = 12;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required int32 status = 12;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 12;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000800;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 12;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000800);
        status_ = 0;
        onChanged();
        return this;
      }

      private com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO user_ = com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO, com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.Builder, com.yumfee.extremeworld.proto.UserMinProto.UserMinDTOOrBuilder> userBuilder_;
      /**
       * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
       */
      public com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO getUser() {
        if (userBuilder_ == null) {
          return user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
       */
      public Builder setUser(com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      /**
       * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
       */
      public Builder setUser(
          com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      /**
       * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
       */
      public Builder mergeUser(com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00001000) == 0x00001000) &&
              user_ != com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.getDefaultInstance()) {
            user_ =
              com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      /**
       * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.getDefaultInstance();
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }
      /**
       * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
       */
      public com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.Builder getUserBuilder() {
        bitField0_ |= 0x00001000;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
       */
      public com.yumfee.extremeworld.proto.UserMinProto.UserMinDTOOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_;
        }
      }
      /**
       * <code>required .com.yumfee.extremeworld.proto.UserMinDTO user = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO, com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.Builder, com.yumfee.extremeworld.proto.UserMinProto.UserMinDTOOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO, com.yumfee.extremeworld.proto.UserMinProto.UserMinDTO.Builder, com.yumfee.extremeworld.proto.UserMinProto.UserMinDTOOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO videoDetail_ = com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO, com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.Builder, com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTOOrBuilder> videoDetailBuilder_;
      /**
       * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
       */
      public boolean hasVideoDetail() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
       */
      public com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO getVideoDetail() {
        if (videoDetailBuilder_ == null) {
          return videoDetail_;
        } else {
          return videoDetailBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
       */
      public Builder setVideoDetail(com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO value) {
        if (videoDetailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          videoDetail_ = value;
          onChanged();
        } else {
          videoDetailBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00002000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
       */
      public Builder setVideoDetail(
          com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.Builder builderForValue) {
        if (videoDetailBuilder_ == null) {
          videoDetail_ = builderForValue.build();
          onChanged();
        } else {
          videoDetailBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00002000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
       */
      public Builder mergeVideoDetail(com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO value) {
        if (videoDetailBuilder_ == null) {
          if (((bitField0_ & 0x00002000) == 0x00002000) &&
              videoDetail_ != com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.getDefaultInstance()) {
            videoDetail_ =
              com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.newBuilder(videoDetail_).mergeFrom(value).buildPartial();
          } else {
            videoDetail_ = value;
          }
          onChanged();
        } else {
          videoDetailBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00002000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
       */
      public Builder clearVideoDetail() {
        if (videoDetailBuilder_ == null) {
          videoDetail_ = com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.getDefaultInstance();
          onChanged();
        } else {
          videoDetailBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
       */
      public com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.Builder getVideoDetailBuilder() {
        bitField0_ |= 0x00002000;
        onChanged();
        return getVideoDetailFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
       */
      public com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTOOrBuilder getVideoDetailOrBuilder() {
        if (videoDetailBuilder_ != null) {
          return videoDetailBuilder_.getMessageOrBuilder();
        } else {
          return videoDetail_;
        }
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.VideoDetailDTO videoDetail = 14;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO, com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.Builder, com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTOOrBuilder> 
          getVideoDetailFieldBuilder() {
        if (videoDetailBuilder_ == null) {
          videoDetailBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO, com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.Builder, com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTOOrBuilder>(
                  getVideoDetail(),
                  getParentForChildren(),
                  isClean());
          videoDetail_ = null;
        }
        return videoDetailBuilder_;
      }

      private com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO mediaWrap_ = com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO, com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.Builder, com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTOOrBuilder> mediaWrapBuilder_;
      /**
       * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
       */
      public boolean hasMediaWrap() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
       */
      public com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO getMediaWrap() {
        if (mediaWrapBuilder_ == null) {
          return mediaWrap_;
        } else {
          return mediaWrapBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
       */
      public Builder setMediaWrap(com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO value) {
        if (mediaWrapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mediaWrap_ = value;
          onChanged();
        } else {
          mediaWrapBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00004000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
       */
      public Builder setMediaWrap(
          com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.Builder builderForValue) {
        if (mediaWrapBuilder_ == null) {
          mediaWrap_ = builderForValue.build();
          onChanged();
        } else {
          mediaWrapBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00004000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
       */
      public Builder mergeMediaWrap(com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO value) {
        if (mediaWrapBuilder_ == null) {
          if (((bitField0_ & 0x00004000) == 0x00004000) &&
              mediaWrap_ != com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.getDefaultInstance()) {
            mediaWrap_ =
              com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.newBuilder(mediaWrap_).mergeFrom(value).buildPartial();
          } else {
            mediaWrap_ = value;
          }
          onChanged();
        } else {
          mediaWrapBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00004000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
       */
      public Builder clearMediaWrap() {
        if (mediaWrapBuilder_ == null) {
          mediaWrap_ = com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.getDefaultInstance();
          onChanged();
        } else {
          mediaWrapBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
       */
      public com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.Builder getMediaWrapBuilder() {
        bitField0_ |= 0x00004000;
        onChanged();
        return getMediaWrapFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
       */
      public com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTOOrBuilder getMediaWrapOrBuilder() {
        if (mediaWrapBuilder_ != null) {
          return mediaWrapBuilder_.getMessageOrBuilder();
        } else {
          return mediaWrap_;
        }
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.MediaWrapDTO mediaWrap = 15;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO, com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.Builder, com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTOOrBuilder> 
          getMediaWrapFieldBuilder() {
        if (mediaWrapBuilder_ == null) {
          mediaWrapBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO, com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTO.Builder, com.yumfee.extremeworld.proto.MediaWrapProto.MediaWrapDTOOrBuilder>(
                  getMediaWrap(),
                  getParentForChildren(),
                  isClean());
          mediaWrap_ = null;
        }
        return mediaWrapBuilder_;
      }

      private com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO taxonomy_ = com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO, com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.Builder, com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTOOrBuilder> taxonomyBuilder_;
      /**
       * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
       */
      public boolean hasTaxonomy() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
       */
      public com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO getTaxonomy() {
        if (taxonomyBuilder_ == null) {
          return taxonomy_;
        } else {
          return taxonomyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
       */
      public Builder setTaxonomy(com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO value) {
        if (taxonomyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          taxonomy_ = value;
          onChanged();
        } else {
          taxonomyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
       */
      public Builder setTaxonomy(
          com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.Builder builderForValue) {
        if (taxonomyBuilder_ == null) {
          taxonomy_ = builderForValue.build();
          onChanged();
        } else {
          taxonomyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
       */
      public Builder mergeTaxonomy(com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO value) {
        if (taxonomyBuilder_ == null) {
          if (((bitField0_ & 0x00008000) == 0x00008000) &&
              taxonomy_ != com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.getDefaultInstance()) {
            taxonomy_ =
              com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.newBuilder(taxonomy_).mergeFrom(value).buildPartial();
          } else {
            taxonomy_ = value;
          }
          onChanged();
        } else {
          taxonomyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
       */
      public Builder clearTaxonomy() {
        if (taxonomyBuilder_ == null) {
          taxonomy_ = com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.getDefaultInstance();
          onChanged();
        } else {
          taxonomyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
       */
      public com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.Builder getTaxonomyBuilder() {
        bitField0_ |= 0x00008000;
        onChanged();
        return getTaxonomyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
       */
      public com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTOOrBuilder getTaxonomyOrBuilder() {
        if (taxonomyBuilder_ != null) {
          return taxonomyBuilder_.getMessageOrBuilder();
        } else {
          return taxonomy_;
        }
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.TaxonomyDTO taxonomy = 16;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO, com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.Builder, com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTOOrBuilder> 
          getTaxonomyFieldBuilder() {
        if (taxonomyBuilder_ == null) {
          taxonomyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO, com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTO.Builder, com.yumfee.extremeworld.proto.TaxonomyProto.TaxonomyDTOOrBuilder>(
                  getTaxonomy(),
                  getParentForChildren(),
                  isClean());
          taxonomy_ = null;
        }
        return taxonomyBuilder_;
      }

      private com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO course_ = com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO, com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.Builder, com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTOOrBuilder> courseBuilder_;
      /**
       * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
       */
      public boolean hasCourse() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
       */
      public com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO getCourse() {
        if (courseBuilder_ == null) {
          return course_;
        } else {
          return courseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
       */
      public Builder setCourse(com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO value) {
        if (courseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          course_ = value;
          onChanged();
        } else {
          courseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
       */
      public Builder setCourse(
          com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.Builder builderForValue) {
        if (courseBuilder_ == null) {
          course_ = builderForValue.build();
          onChanged();
        } else {
          courseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
       */
      public Builder mergeCourse(com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO value) {
        if (courseBuilder_ == null) {
          if (((bitField0_ & 0x00010000) == 0x00010000) &&
              course_ != com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.getDefaultInstance()) {
            course_ =
              com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.newBuilder(course_).mergeFrom(value).buildPartial();
          } else {
            course_ = value;
          }
          onChanged();
        } else {
          courseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
       */
      public Builder clearCourse() {
        if (courseBuilder_ == null) {
          course_ = com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.getDefaultInstance();
          onChanged();
        } else {
          courseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
       */
      public com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.Builder getCourseBuilder() {
        bitField0_ |= 0x00010000;
        onChanged();
        return getCourseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
       */
      public com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTOOrBuilder getCourseOrBuilder() {
        if (courseBuilder_ != null) {
          return courseBuilder_.getMessageOrBuilder();
        } else {
          return course_;
        }
      }
      /**
       * <code>optional .com.yumfee.extremeworld.proto.CourseMinDTO course = 17;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO, com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.Builder, com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTOOrBuilder> 
          getCourseFieldBuilder() {
        if (courseBuilder_ == null) {
          courseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO, com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTO.Builder, com.yumfee.extremeworld.proto.CourseMinProto.CourseMinDTOOrBuilder>(
                  getCourse(),
                  getParentForChildren(),
                  isClean());
          course_ = null;
        }
        return courseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.yumfee.extremeworld.proto.TopicDTO)
    }

    static {
      defaultInstance = new TopicDTO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.yumfee.extremeworld.proto.TopicDTO)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yumfee_extremeworld_proto_TopicDTO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_yumfee_extremeworld_proto_TopicDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016TopicDTO.proto\022\035com.yumfee.extremeworl" +
      "d.proto\032\020UserMinDTO.proto\032\024VideoDetailDT" +
      "O.proto\032\022MediaWrapDTO.proto\032\021TaxonomyDTO" +
      ".proto\032\022CourseMinDTO.proto\"\231\004\n\010TopicDTO\022" +
      "\n\n\002id\030\001 \002(\003\022\014\n\004type\030\002 \002(\t\022\021\n\tmagicType\030\003" +
      " \001(\t\022\r\n\005title\030\004 \002(\t\022\017\n\007content\030\005 \002(\t\022\022\n\n" +
      "imageCount\030\006 \002(\005\022\022\n\nreplyCount\030\007 \002(\005\022\025\n\r" +
      "allReplyCount\030\010 \002(\005\022\021\n\tviewCount\030\t \002(\005\022\022" +
      "\n\nagreeCount\030\n \002(\005\022\022\n\ncreateTime\030\013 \002(\t\022\016" +
      "\n\006status\030\014 \002(\005\0227\n\004user\030\r \002(\0132).com.yumfe",
      "e.extremeworld.proto.UserMinDTO\022B\n\013video" +
      "Detail\030\016 \001(\0132-.com.yumfee.extremeworld.p" +
      "roto.VideoDetailDTO\022>\n\tmediaWrap\030\017 \001(\0132+" +
      ".com.yumfee.extremeworld.proto.MediaWrap" +
      "DTO\022<\n\010taxonomy\030\020 \001(\0132*.com.yumfee.extre" +
      "meworld.proto.TaxonomyDTO\022;\n\006course\030\021 \001(" +
      "\0132+.com.yumfee.extremeworld.proto.Course" +
      "MinDTOB+\n\035com.yumfee.extremeworld.protoB" +
      "\nTopicProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yumfee.extremeworld.proto.UserMinProto.getDescriptor(),
          com.yumfee.extremeworld.proto.VideoDetailProto.getDescriptor(),
          com.yumfee.extremeworld.proto.MediaWrapProto.getDescriptor(),
          com.yumfee.extremeworld.proto.TaxonomyProto.getDescriptor(),
          com.yumfee.extremeworld.proto.CourseMinProto.getDescriptor(),
        }, assigner);
    internal_static_com_yumfee_extremeworld_proto_TopicDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yumfee_extremeworld_proto_TopicDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_yumfee_extremeworld_proto_TopicDTO_descriptor,
        new java.lang.String[] { "Id", "Type", "MagicType", "Title", "Content", "ImageCount", "ReplyCount", "AllReplyCount", "ViewCount", "AgreeCount", "CreateTime", "Status", "User", "VideoDetail", "MediaWrap", "Taxonomy", "Course", });
    com.yumfee.extremeworld.proto.UserMinProto.getDescriptor();
    com.yumfee.extremeworld.proto.VideoDetailProto.getDescriptor();
    com.yumfee.extremeworld.proto.MediaWrapProto.getDescriptor();
    com.yumfee.extremeworld.proto.TaxonomyProto.getDescriptor();
    com.yumfee.extremeworld.proto.CourseMinProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
