// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoDetailDTO.proto

package com.yumfee.extremeworld.proto;

public final class VideoDetailProto {
  private VideoDetailProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VideoDetailDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yumfee.extremeworld.proto.VideoDetailDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required string videoSource = 2;</code>
     */
    boolean hasVideoSource();
    /**
     * <code>required string videoSource = 2;</code>
     */
    java.lang.String getVideoSource();
    /**
     * <code>required string videoSource = 2;</code>
     */
    com.google.protobuf.ByteString
        getVideoSourceBytes();

    /**
     * <code>optional string thumbnail = 3;</code>
     */
    boolean hasThumbnail();
    /**
     * <code>optional string thumbnail = 3;</code>
     */
    java.lang.String getThumbnail();
    /**
     * <code>optional string thumbnail = 3;</code>
     */
    com.google.protobuf.ByteString
        getThumbnailBytes();
  }
  /**
   * Protobuf type {@code com.yumfee.extremeworld.proto.VideoDetailDTO}
   */
  public static final class VideoDetailDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.yumfee.extremeworld.proto.VideoDetailDTO)
      VideoDetailDTOOrBuilder {
    // Use VideoDetailDTO.newBuilder() to construct.
    private VideoDetailDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VideoDetailDTO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VideoDetailDTO defaultInstance;
    public static VideoDetailDTO getDefaultInstance() {
      return defaultInstance;
    }

    public VideoDetailDTO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VideoDetailDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              videoSource_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              thumbnail_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yumfee.extremeworld.proto.VideoDetailProto.internal_static_com_yumfee_extremeworld_proto_VideoDetailDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yumfee.extremeworld.proto.VideoDetailProto.internal_static_com_yumfee_extremeworld_proto_VideoDetailDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.class, com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.Builder.class);
    }

    public static com.google.protobuf.Parser<VideoDetailDTO> PARSER =
        new com.google.protobuf.AbstractParser<VideoDetailDTO>() {
      public VideoDetailDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VideoDetailDTO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VideoDetailDTO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int VIDEOSOURCE_FIELD_NUMBER = 2;
    private java.lang.Object videoSource_;
    /**
     * <code>required string videoSource = 2;</code>
     */
    public boolean hasVideoSource() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string videoSource = 2;</code>
     */
    public java.lang.String getVideoSource() {
      java.lang.Object ref = videoSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          videoSource_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string videoSource = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVideoSourceBytes() {
      java.lang.Object ref = videoSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        videoSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int THUMBNAIL_FIELD_NUMBER = 3;
    private java.lang.Object thumbnail_;
    /**
     * <code>optional string thumbnail = 3;</code>
     */
    public boolean hasThumbnail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string thumbnail = 3;</code>
     */
    public java.lang.String getThumbnail() {
      java.lang.Object ref = thumbnail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          thumbnail_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string thumbnail = 3;</code>
     */
    public com.google.protobuf.ByteString
        getThumbnailBytes() {
      java.lang.Object ref = thumbnail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        thumbnail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0L;
      videoSource_ = "";
      thumbnail_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVideoSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getVideoSourceBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getThumbnailBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getVideoSourceBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getThumbnailBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yumfee.extremeworld.proto.VideoDetailDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yumfee.extremeworld.proto.VideoDetailDTO)
        com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yumfee.extremeworld.proto.VideoDetailProto.internal_static_com_yumfee_extremeworld_proto_VideoDetailDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yumfee.extremeworld.proto.VideoDetailProto.internal_static_com_yumfee_extremeworld_proto_VideoDetailDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.class, com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.Builder.class);
      }

      // Construct using com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        videoSource_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        thumbnail_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yumfee.extremeworld.proto.VideoDetailProto.internal_static_com_yumfee_extremeworld_proto_VideoDetailDTO_descriptor;
      }

      public com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO getDefaultInstanceForType() {
        return com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.getDefaultInstance();
      }

      public com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO build() {
        com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO buildPartial() {
        com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO result = new com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.videoSource_ = videoSource_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.thumbnail_ = thumbnail_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO) {
          return mergeFrom((com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO other) {
        if (other == com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasVideoSource()) {
          bitField0_ |= 0x00000002;
          videoSource_ = other.videoSource_;
          onChanged();
        }
        if (other.hasThumbnail()) {
          bitField0_ |= 0x00000004;
          thumbnail_ = other.thumbnail_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasVideoSource()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yumfee.extremeworld.proto.VideoDetailProto.VideoDetailDTO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object videoSource_ = "";
      /**
       * <code>required string videoSource = 2;</code>
       */
      public boolean hasVideoSource() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string videoSource = 2;</code>
       */
      public java.lang.String getVideoSource() {
        java.lang.Object ref = videoSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            videoSource_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string videoSource = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVideoSourceBytes() {
        java.lang.Object ref = videoSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          videoSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string videoSource = 2;</code>
       */
      public Builder setVideoSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        videoSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string videoSource = 2;</code>
       */
      public Builder clearVideoSource() {
        bitField0_ = (bitField0_ & ~0x00000002);
        videoSource_ = getDefaultInstance().getVideoSource();
        onChanged();
        return this;
      }
      /**
       * <code>required string videoSource = 2;</code>
       */
      public Builder setVideoSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        videoSource_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object thumbnail_ = "";
      /**
       * <code>optional string thumbnail = 3;</code>
       */
      public boolean hasThumbnail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string thumbnail = 3;</code>
       */
      public java.lang.String getThumbnail() {
        java.lang.Object ref = thumbnail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            thumbnail_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string thumbnail = 3;</code>
       */
      public com.google.protobuf.ByteString
          getThumbnailBytes() {
        java.lang.Object ref = thumbnail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          thumbnail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string thumbnail = 3;</code>
       */
      public Builder setThumbnail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        thumbnail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string thumbnail = 3;</code>
       */
      public Builder clearThumbnail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        thumbnail_ = getDefaultInstance().getThumbnail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string thumbnail = 3;</code>
       */
      public Builder setThumbnailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        thumbnail_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.yumfee.extremeworld.proto.VideoDetailDTO)
    }

    static {
      defaultInstance = new VideoDetailDTO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.yumfee.extremeworld.proto.VideoDetailDTO)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yumfee_extremeworld_proto_VideoDetailDTO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_yumfee_extremeworld_proto_VideoDetailDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024VideoDetailDTO.proto\022\035com.yumfee.extre" +
      "meworld.proto\"D\n\016VideoDetailDTO\022\n\n\002id\030\001 " +
      "\002(\003\022\023\n\013videoSource\030\002 \002(\t\022\021\n\tthumbnail\030\003 " +
      "\001(\tB1\n\035com.yumfee.extremeworld.protoB\020Vi" +
      "deoDetailProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_yumfee_extremeworld_proto_VideoDetailDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yumfee_extremeworld_proto_VideoDetailDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_yumfee_extremeworld_proto_VideoDetailDTO_descriptor,
        new java.lang.String[] { "Id", "VideoSource", "Thumbnail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
